# GitHub Action for PHP File Cache Simple by HungNG
name: Testing PHP File Cache Simple by HungNG
on: [ push, pull_request ]
jobs:
    build:
        strategy:
            matrix:
                operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
                php-versions: [ '5.4', '5.6', '7.0', '8.0' ]
        runs-on: ${{ matrix.operating-system }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2 # From https://github.com/shivammathur/setup-php
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: mbstring, intl, curl, json, openssl, iconv, fileinfo
                    coverage: xdebug #optional
            -   name: Get composer cache directory
                id: composercache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   name: Cache composer dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    # Use composer.json for key, if composer.lock is not committed.
                    # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -   name: Install dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader
            -   name: Test Simple Cache
                run: php ./examples/simple_cache.php
            -   name: Test Simple Cache with Meta
                run: php ./examples/simple_cache_meta.php
            -   name: Test Simple Cache Traditional Style
                run: php ./examples/simple_cache_traditional.php